openapi: 3.0.0
info:
  title: hello
  version: 0.0.1
  description: This is my first App
  contact:
    name: sachinsharma0237
    email: sachinsharma0237@gmail.com
paths:
  /hello-world:
    get:
      x-controller-name: HelloWorldController
      x-operation-name: sayHello
      tags:
        - HelloWorldController
      responses:
        '200':
          description: This is our new description
          content:
            application/json:
              schema:
                type: string
      operationId: HelloWorldController.sayHello
  /ping:
    get:
      x-controller-name: PingController
      x-operation-name: ping
      tags:
        - PingController
      responses:
        '200':
          description: Ping Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
      operationId: PingController.ping
servers:
  - url: /
components:
  schemas:
    PingResponse:
      type: object
      title: PingResponse
      properties:
        greeting:
          type: string
        date:
          type: string
        url:
          type: string
        headers:
          type: object
          properties:
            Content-Type:
              type: string
          additionalProperties: true
